### ISSUE TITLE
Can't start the project using Visual Studio

### ISSUE THREAD

**Issue by hintdesk** [erwinkramer/bank-api#5]
Hi,

I would like to ask if someone can run the code with Visual Studio with **https**?
I can start the solution with http but if I try with https, I receive this error. 

`
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 9.0.0+01ed51919f8df692ececce51048a140615dc759d
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\Temp\BankApi\bank-api\BankApi.Orchestration
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: https://localhost:17109
info: Aspire.Hosting.DistributedApplication[0]
      Login to the dashboard at https://localhost:17109/login?t=a21d6a037fe27547c37c5de85c1fc0a4
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
fail: Aspire.Hosting.Dashboard.Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.IO.IOException: Failed to bind to address https://localhost:21159.
       ---> System.AggregateException: One or more errors occurred. (Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.) (Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.)
       ---> System.Net.Sockets.SocketException (10013): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
       ---> (Inner Exception #1) System.Net.Sockets.SocketException (10013): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)<---

         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9610000Z Unhandled exception. System.IO.IOException: Failed to bind to address https://localhost:21159.
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z  ---> System.AggregateException: One or more errors occurred. (Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzul?ssig.) (Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzul?ssig.)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z  ---> System.Net.Sockets.SocketException (10013): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzul?ssig.
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z --- End of stack trace from previous location ---
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    --- End of inner exception stack trace ---
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z  ---> (Inner Exception #1) System.Net.Sockets.SocketException (10013): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzul?ssig.
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z --- End of stack trace from previous location ---
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)<---
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    --- End of inner exception stack trace ---
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Aspire.Dashboard.DashboardWebApplication.Run() in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 848
fail: Aspire.Hosting.Dashboard[0]
      2024-12-29T08:29:40.9680000Z    at Program.<Main>$(String[] args) in /_/src/Aspire.Dashboard/Program.cs:line 7
`

I have no clue how I can fix the error. The storage can be created in Docker Runtime.

<img width="730" alt="{9425F398-0E95-428E-9A09-D22E2B434FD6}" src="https://github.com/user-attachments/assets/ec996b60-f0bc-463d-ac41-773922c3f9cd" />

Does anyone has the same problem as I do?

Thank you.

**Comment by erwinkramer** [comment]
Please check https://github.com/dotnet/aspire/issues/5112#issuecomment-2323206713

So maybe it's still in use by a previous debugging session. I never experienced this myself but I'm using vscode primarily, so maybe try that as well (after cleaning all existing debugging processes).

**Comment by erwinkramer** [comment]
@hintdesk just checked on my machine, if i run with https on `Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.13.0 Preview 1.0`, and on `Version 17.13.0 Preview 2.1`, i get no errors. Please check my previous comment and try to double check if you run the latest versions of VS and .NET 9.

**Comment by erwinkramer** [comment]
Feel free to reopen if it's still an issue. Closing this now.
